module.exports = {
  LOGIN_NUMBER_REQUEST: 'LOGIN_NUMBER_REQUEST',
  LOGIN_NUMBER_SUCCESS: 'LOGIN_NUMBER_SUCCESS',
  LOGIN_NUMBER_FAILURE: 'LOGIN_NUMBER_FAILURE',
  LOGIN_CODE_REQUEST: 'LOGIN_CODE_REQUEST',
  LOGIN_CODE_FAILURE: 'LOGIN_CODE_FAILURE',

  LOGIN_ALL_SUCCESS: 'LOGIN_ALL_SUCCESS',

  GET_CHATS_REQUEST: 'GET_CHATS_REQUEST',
  GET_CHATS_RESPONSE: 'GET_CHATS_RESPONSE',
};
