module.exports = {
  LOGIN_NUMBER_REQUEST: 'LOGIN_NUMBER_REQUEST',
  LOGIN_NUMBER_SUCCESS: 'LOGIN_NUMBER_SUCCESS',
  LOGIN_NUMBER_FAILURE: 'LOGIN_NUMBER_FAILURE',
  LOGIN_CODE_REQUEST: 'LOGIN_CODE_REQUEST',
  LOGIN_CODE_FAILURE: 'LOGIN_CODE_FAILURE',
  LOGIN_ALL_SUCCESS: 'LOGIN_ALL_SUCCESS',

  LOVENSE_SETTINGS_SAVE: 'LOVENSE_SETTINGS_SAVE',
  LOVENSE_SETTINGS_SAVED: 'LOVENSE_SETTINGS_SAVED',
  LOVENSE_SETTINGS_FAILED: 'LOVENSE_SETTINGS_FAILED',

  LOVENSE_TEST_RUN: 'LOVENSE_TEST_RUN',
  LOVENSE_TEST_COMPLETE: 'LOVENSE_TEST_COMPLETE',
  LOVENSE_TEST_FAILED: 'LOVENSE_TEST_FAILED',

  GET_CHATS_REQUEST: 'GET_CHATS_REQUEST',
  GET_CHATS_RESPONSE: 'GET_CHATS_RESPONSE',
};
